import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/chat_message.dart';
import '../omni/tool_executor.dart';
import '../providers/chat_history_provider.dart';
import '../providers/lemonade_client_provider.dart';
import '../providers/model_defaults_provider.dart';
import '../providers/models_provider.dart';
import '../providers/omni_router_provider.dart';
import '../services/duplex_voice_session.dart';
import '../storage/file_storage.dart';

/// Phone-call-style voice conversation. Pushes as a full-screen route from the
/// chat screen. Uses the active server + selected LLM, plus the configured ASR
/// and TTS models from `globalModelDefaultsProvider`.
class TalkScreen extends ConsumerStatefulWidget {
  const TalkScreen({super.key});

  @override
  ConsumerState<TalkScreen> createState() => _TalkScreenState();
}

class _TalkScreenState extends ConsumerState<TalkScreen>
    with SingleTickerProviderStateMixin {
  DuplexVoiceSession? _session;
  StreamSubscription? _stateSub;
  StreamSubscription? _eventSub;
  late final AnimationController _pulse;

  DuplexState _state = DuplexState.idle;
  String _interim = '';
  String _lastUser = '';
  String _lastAssistant = '';
  String? _error;
  // Artifacts produced this call. Folded into chat history on hang-up so the
  // user sees images / audio the LLM generated by tool call.
  final List<Artifact> _callArtifacts = [];

  @override
  void initState() {
    super.initState();
    _pulse = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 900),
    )..repeat(reverse: true);
    WidgetsBinding.instance.addPostFrameCallback((_) => _start());
  }

  Future<void> _start() async {
    final client = ref.read(lemonadeClientProvider);
    // Use the wire LLM — collapses Collections to their chat-shaped
    // component so the chat call doesn't 500 on the meta-id.
    final llm = ref.read(wireLlmModelProvider);
    if (client == null || llm == null) {
      setState(() => _error = 'Select a server and model first.');
      return;
    }
    final defaults = ref.read(globalModelDefaultsProvider);
    final asr = defaults.audioToTextModel ?? _firstByCapability((m) => m.supportsAudio);
    final tts = defaults.textToAudioModel ?? _firstByCapability((m) => m.supportsTts);
    if (asr == null) {
      setState(() => _error = 'No audio-to-text model is loaded on the server.');
      return;
    }

    final history = ref.read(chatHistoryProvider.notifier).getActiveChat()?.messages ??
        const <ChatMessage>[];

    final caps = ref.read(omniCapabilitiesProvider);
    final exec = ref.read(omniToolExecutorProvider);

    final session = DuplexVoiceSession(
      client: client,
      llmModel: llm,
      asrModel: asr,
      ttsModel: tts,
      history: List.of(history),
      capabilities: caps,
      executor: exec,
    );
    _session = session;

    _stateSub = session.state.listen((s) {
      if (!mounted) return;
      setState(() => _state = s);
    });
    _eventSub = session.events.listen((ev) {
      if (!mounted) return;
      setState(() {
        switch (ev) {
          case DuplexTranscriptUpdate():
            _interim = ev.text;
          case DuplexUserSpoke():
            _lastUser = ev.text;
            _interim = '';
          case DuplexAssistantSpoke():
            _lastAssistant = ev.text;
          case DuplexArtifactEvent():
            _callArtifacts.add(ev.artifact);
          case DuplexErrorEvent():
            _error = ev.message;
        }
      });
    });

    try {
      await session.start();
    } catch (e) {
      if (!mounted) return;
      setState(() => _error = 'Failed to start: $e');
    }
  }

  String? _firstByCapability(bool Function(ModelInfo) test) {
    final models = ref.read(modelsProvider);
    for (final m in models) {
      if (test(m)) return m.id;
    }
    return null;
  }

  Future<void> _hangUp() async {
    await _session?.stop();
    if (!mounted) return;

    if (_lastUser.isNotEmpty) {
      final notifier = ref.read(chatHistoryProvider.notifier);
      final active = notifier.getActiveChat();
      if (active != null) {
        final assistantParts = <MessageContent>[];
        if (_lastAssistant.isNotEmpty) {
          assistantParts.add(
            MessageContent(type: MessageContentType.text, value: _lastAssistant),
          );
        }
        for (final art in _callArtifacts) {
          final url = 'data:${art.mime};base64,${art.base64Data}';
          assistantParts.add(MessageContent(
            type: art.kind == ArtifactKind.image
                ? MessageContentType.image
                : MessageContentType.audio,
            value: url,
          ));
          // Persist the binary so the chat survives app restarts.
          try {
            await AttachmentStore.writeBase64(
              base64Data: art.base64Data,
              kind: art.kind == ArtifactKind.image ? 'image' : 'audio',
              extension: '.${art.mime.split('/').last}',
            );
          } catch (_) {}
        }

        final updated = [
          ...active.messages,
          ChatMessage.text(role: MessageRole.user, text: 'Voice: $_lastUser'),
          if (assistantParts.isNotEmpty)
            ChatMessage(role: MessageRole.assistant, content: assistantParts),
        ];
        await notifier.updateActiveChat(updated);
      }
    }

    if (mounted) Navigator.of(context).pop();
  }

  @override
  void dispose() {
    _stateSub?.cancel();
    _eventSub?.cancel();
    _session?.dispose();
    _pulse.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: scheme.surface,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            children: [
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: _hangUp,
                  ),
                  const Spacer(),
                  Text('Talk',
                      style: Theme.of(context).textTheme.titleLarge),
                  const Spacer(),
                  const SizedBox(width: 48),
                ],
              ),
              const Spacer(),
              _StatusIndicator(state: _state, pulse: _pulse, scheme: scheme),
              const SizedBox(height: 24),
              Text(
                _statusLabel(),
                style: Theme.of(context).textTheme.titleMedium,
              ),
              const SizedBox(height: 32),
              if (_lastAssistant.isNotEmpty)
                _Bubble(
                  text: _lastAssistant,
                  alignRight: false,
                  color: scheme.surfaceContainerHigh,
                  textColor: scheme.onSurface,
                ),
              if (_lastUser.isNotEmpty) ...[
                const SizedBox(height: 8),
                _Bubble(
                  text: _lastUser,
                  alignRight: true,
                  color: scheme.primary,
                  textColor: scheme.onPrimary,
                ),
              ],
              if (_interim.isNotEmpty) ...[
                const SizedBox(height: 8),
                _Bubble(
                  text: _interim,
                  alignRight: true,
                  color: scheme.primary.withValues(alpha: 0.4),
                  textColor: scheme.onPrimary,
                ),
              ],
              const Spacer(),
              if (_error != null)
                Padding(
                  padding: const EdgeInsets.only(bottom: 16),
                  child: Text(
                    _error!,
                    style: TextStyle(color: scheme.error),
                  ),
                ),
              ElevatedButton.icon(
                onPressed: _hangUp,
                icon: const Icon(Icons.call_end),
                label: const Text('End call'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.redAccent,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _statusLabel() {
    switch (_state) {
      case DuplexState.connecting:
        return 'Connecting…';
      case DuplexState.listening:
        return 'Listening…';
      case DuplexState.thinking:
        return 'Thinking…';
      case DuplexState.speaking:
        return 'Speaking…';
      case DuplexState.idle:
        return 'Idle';
    }
  }
}

class _StatusIndicator extends StatelessWidget {
  final DuplexState state;
  final AnimationController pulse;
  final ColorScheme scheme;

  const _StatusIndicator({
    required this.state,
    required this.pulse,
    required this.scheme,
  });

  @override
  Widget build(BuildContext context) {
    final color = switch (state) {
      DuplexState.listening => scheme.primary,
      DuplexState.thinking => Colors.amber,
      DuplexState.speaking => Colors.greenAccent,
      DuplexState.connecting => scheme.outline,
      DuplexState.idle => scheme.outline,
    };
    final icon = switch (state) {
      DuplexState.listening => Icons.mic,
      DuplexState.thinking => Icons.psychology_alt,
      DuplexState.speaking => Icons.graphic_eq,
      DuplexState.connecting => Icons.cable,
      DuplexState.idle => Icons.call,
    };
    return AnimatedBuilder(
      animation: pulse,
      builder: (context, _) {
        final t = pulse.value;
        return Container(
          width: 160,
          height: 160,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: color.withValues(alpha: 0.12),
            boxShadow: [
              BoxShadow(
                color: color.withValues(alpha: 0.5 * t),
                blurRadius: 32 + (t * 16),
                spreadRadius: 4 + (t * 4),
              ),
            ],
          ),
          child: Center(
            child: Container(
              width: 120,
              height: 120,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: color.withValues(alpha: 0.25 + (t * 0.2)),
              ),
              child: Icon(icon, color: color, size: 56),
            ),
          ),
        );
      },
    );
  }
}

class _Bubble extends StatelessWidget {
  final String text;
  final bool alignRight;
  final Color color;
  final Color textColor;

  const _Bubble({
    required this.text,
    required this.alignRight,
    required this.color,
    required this.textColor,
  });

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: alignRight ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.8),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(16),
        ),
        child: Text(text, style: TextStyle(color: textColor, fontSize: 15)),
      ),
    );
  }
}
